keycloak:
  url: ${CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL}
  realm: ${CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM}
  client-id: ${CAMUNDA_OPERATE_CLIENT_CLIENT-ID}
  client-secret: ${CAMUNDA_OPERATE_CLIENT_CLIENT-SECRET}