keycloak:
  url: ${CAMUNDA_OPERATE_CLIENT_KEYCLOAK-URL}
  realm: ${CAMUNDA_OPERATE_CLIENT_KEYCLOAK-REALM}
  client-id: ${CAMUNDA_IDENTITY_CLIENT_ID}
  client-secret: ${CAMUNDA_IDENTITY_CLIENT_SECRET}
